### PR TITLE
feat: connect wallet widget, closes issue #8

### PR DESCRIPTION
**Pull request by creativogee**
## Description
Closes issue #8 
### This commit contains
- Interactable and fully responsive wallet connect widget, which overlays the screen on clicking the "connect wallet" button.
- A responsive skeleton placeholder for the assets listing. This fixes the bump during painting.

### CODE REVIEW

**Comment by jmulq** [comment]
Should this PR include wiring up the component to blockchain connection via metmask and wallet connect?

**Review by jmulq — COMMENTED** [review]
See prev comment

**Comment by anjorinjnr** [comment]
What is happening here? @abbeydabiri  can you help finish the implementation so we can check this in. Thanks

**Comment by betterchalk-gbenga** [comment]
> What is happening here? @abbeydabiri can you help finish the implementation so we can check this in. Thanks

This PR is currently placed on hold for PR #65 to go through so I can rebase this one on it. #65 has caching and redux married. I already have the implementation for the connection for metamask and wallet connect using web3-react on ground

**Comment by creativogee** [comment]
> What is happening here? @abbeydabiri can you help finish the implementation so we can check this in. Thanks

@anjorinjnr It's a file, are you suggesting it is changed to folder called file. Also we have a file called types already. Should we put the enums and the types together in the types.ts file/types folder?

**Comment by jmulq** [comment]
Why has this been closed? Isn't @abbeydabiri now working against this branch and PR?

**Pull request closed without merging**
